[2025-08-29T02:35:04.447+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulate_inference_to_mlflow.simulate_and_log scheduled__2025-08-29T02:34:00+00:00 [queued]>
[2025-08-29T02:35:04.460+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulate_inference_to_mlflow.simulate_and_log scheduled__2025-08-29T02:34:00+00:00 [queued]>
[2025-08-29T02:35:04.461+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-29T02:35:04.481+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): simulate_and_log> on 2025-08-29 02:34:00+00:00
[2025-08-29T02:35:04.491+0000] {standard_task_runner.py:60} INFO - Started process 650 to run task
[2025-08-29T02:35:04.495+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'simulate_inference_to_mlflow', 'simulate_and_log', 'scheduled__2025-08-29T02:34:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/simulate_inference_dags.py', '--cfg-path', '/tmp/tmpj5dxhymf']
[2025-08-29T02:35:04.498+0000] {standard_task_runner.py:88} INFO - Job 46: Subtask simulate_and_log
[2025-08-29T02:35:04.565+0000] {task_command.py:423} INFO - Running <TaskInstance: simulate_inference_to_mlflow.simulate_and_log scheduled__2025-08-29T02:34:00+00:00 [running]> on host 81242c1f8e6d
[2025-08-29T02:35:04.687+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops' AIRFLOW_CTX_DAG_ID='simulate_inference_to_mlflow' AIRFLOW_CTX_TASK_ID='simulate_and_log' AIRFLOW_CTX_EXECUTION_DATE='2025-08-29T02:34:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-29T02:34:00+00:00'
[2025-08-29T02:36:05.058+0000] {logging_mixin.py:188} WARNING - 2025/08/29 02:36:05 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-08-29T02:36:06.003+0000] {simulate_inference_dags.py:167} INFO - Logged 10 rows. mean=15.99ms p95=18.31ms ok=0 err=10 saved_to=/opt/***/inference_store/dt=2025-08-29/inference_2025-08-29 02-34-00.csv
[2025-08-29T02:36:06.004+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-29T02:36:06.017+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=simulate_inference_to_mlflow, task_id=simulate_and_log, execution_date=20250829T023400, start_date=20250829T023504, end_date=20250829T023606
[2025-08-29T02:36:06.083+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-29T02:36:06.102+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
